baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Arif Kurniawan Personal Blogs'
theme = 'github-style'
lastmod = true
enableGitalk = false

[params]
  avatar = 'images/profile.png'
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  userStatusEmoji = "ğŸ˜€"
  author = 'Arif Kurniawan'
  github = 'Arifkurniawan200'
  Description = 'Hate Programming and Love Mobile Legend #RoadToMytic'
  location = 'South Jakarta'
  email = 'arifkurniawan200@outlook.co.id'
  linkedin = 'arifkurniawan0906'
  instagram = 'arifkurniawan0609'
  favicon = "/images/github.png"


[params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]